### ISSUE TITLE
Label original point cloud file such like pcd or ply file?

### ISSUE THREAD

**Issue by MikoyChinese** [jbehley/point_labeler#10]
Hi,
Will it support for annotating orinal pointcloud file such like pcd or ply file? I have some data which format is pcd, so how to use  this tool to label the object? I have no idea about it. Please help me.

Thanks,
Mikoy Chinese

**Comment by jbehley** [comment]
Hi,

thanks for your interest in our tool.

Currently, we have no plans to support also other format, since it's hard to decide what is a commonly accepted procedure. (Everyone is somehow using their own standards, etc.)

Thus, I would suggest to convert everything to the KITTI-compatible format and put it in the right folders (see https://github.com/jbehley/point_labeler#folder-structure). The structure of the files is quite simple.

If you need more information, please let me know.

**Comment by MikoyChinese** [comment]
Thanks for your help, I will try to convert my data. Best wishes to you all days.

**Comment by jbehley** [comment]
Let me know if you need more information.

**Comment by SijanNeupane49** [comment]
@MikoyChinese were you able to convert .ply file to .bin (or in KITTI-compatilbe format)? 
@jbehley  Do you maybe know how can I convert .ply files to .bin (or in KITTI-compatible format)?
Thank you both in Advance.
