### ISSUE TITLE
Use Point Labeler for an other dataset

### ISSUE THREAD

**Issue by dev741** [jbehley/point_labeler#23]
Hi, thanks for the open source Tool, very helpful
It works perfectly on SemanticKitti, Now if i need to use an other dataset  that does not contain poses or calibrations  but only point cloud with PLY format? is it possible?  (can i leave the files empty in this way) and how about the labels? how to generate the same format as your Dataset?
Thank you

**Comment by jbehley** [comment]
It's definitely possible to use our tool for other datasets. The simplest way is to just keep the folder structure, convert the ply files to the KITTI bin files, and have dummy files for `poses.txt` and `calib.txt`

`poses.txt` contains for each scan in the velodyne folder a pose. This can also be just the identity, i.e.,  the file contains N times the following line:

```
1 0 0 0 0 1 0 0 0 0 1 0
```
Note that only 12 values are needed because the last row `0 0 0 1` is added.

`calib.txt` contains the calibration file, since in original KITTI the poses are given in the left camera coordinate system and the transformation needed is then the velodye-to-camera transformation called `Tr` in the `calib.txt` file. A dummy calibration file would look as follows:

```
P0: 1 0 0 0 0 1 0 0 0 0 1 0
P1: 1 0 0 0 0 1 0 0 0 0 1 0
P2: 1 0 0 0 0 1 0 0 0 0 1 0
P3: 1 0 0 0 0 1 0 0 0 0 1 0
Tr: 1 0 0 0 0 1 0 0 0 0 1 0
```

As before the last row is appended in the code.

The labels are defined in the file `labels.xml` in the `bin` folder from which the label buttons are generated. You can modify this file as needed. The xml format should be self-explaining, but if you have questions, don't hesitate to write me.

**Comment by dev741** [comment]
Thank you VERY much for these informations,  
Sorry to bother you Sir, but how can i extract the labels from .ply and store them in .label format as the semanticKitti dataset? thank you in advance

**Comment by jbehley** [comment]
Do you mean how to convert the vertex information of a ply file? The corresponding label file is automatically generated by the labeler if it doesn't exist.

In the standard specification (see https://en.m.wikipedia.org/wiki/PLY_(file_format)) there is no label information stored inside a ply file. Could you be more specific?

The label file from SemanticKITTI is very simple: each point of the point cloud gets a label represented as an unsigned int with 32 bits (`np.uint32` in numpy or `uint32_t` under C++).

Hope that helps.

**Comment by dev741** [comment]
Ok thank you so much !
