### ISSUE TITLE
qt error

### ISSUE THREAD

**Issue by ghost** [jbehley/point_labeler#47]
After I run the ./labeler I face this message. my Ubuntu is 20.04.
please help me

QFactoryLoader::QFactoryLoader() checking directory path "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqeglfs.so"
Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqeglfs.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "eglfs"
        ]
    },
    "archreq": 0,
    "className": "QEglFSIntegrationPlugin",
    "debug": false,
    "version": 330752
}

Got keys from plugin meta data ("eglfs")
QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqlinuxfb.so"
Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqlinuxfb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "linuxfb"
        ]
    },
    "archreq": 0,
    "className": "QLinuxFbIntegrationPlugin",
    "debug": false,
    "version": 330752
}

Got keys from plugin meta data ("linuxfb")
QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqminimal.so"
Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqminimal.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimal"
        ]
    },
    "archreq": 0,
    "className": "QMinimalIntegrationPlugin",
    "debug": false,
    "version": 330752
}

Got keys from plugin meta data ("minimal")
QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqminimalegl.so"
Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqminimalegl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimalegl"
        ]
    },
    "archreq": 0,
    "className": "QMinimalEglIntegrationPlugin",
    "debug": false,
    "version": 330752
}

Got keys from plugin meta data ("minimalegl")
QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqoffscreen.so"
Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqoffscreen.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "offscreen"
        ]
    },
    "archreq": 0,
    "className": "QOffscreenIntegrationPlugin",
    "debug": false,
    "version": 330752
}

Got keys from plugin meta data ("offscreen")
QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqvnc.so"
Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqvnc.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "vnc"
        ]
    },
    "archreq": 0,
    "className": "QVncIntegrationPlugin",
    "debug": false,
    "version": 330752
}

Got keys from plugin meta data ("vnc")
QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so"
Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "archreq": 0,
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 330752
}

Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/home/catkin_ws/src/point_labeler/bin/platforms" ...
loaded library "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so"
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Aborted (core dumped)

**Comment by jbehley** [comment]
I currently have no real solution to this problem. But a similar problem we encounter with PySide2, where we had to explicitly set an environment variable QT_API.

However, there seems to be a general problem with the display `qt.qpa.xcb: could not connect to display`; Could it be that you are executing the labeler in a virtual machine or a docker that might cause the problem?

**Comment by didxorkd** [comment]
@jbehley Yes. I was running on it with a docker. When I try to build it without virtual machine or a docker, I continuously fail to build glow. Could you take a look?

`------------------------------------------------------------
Profile:                     default
Extending:                   None
Workspace:                   /home/tackang/catkin_ws
------------------------------------------------------------
Build Space:        [exists] /home/tackang/catkin_ws/build
Devel Space:        [exists] /home/tackang/catkin_ws/devel
Install Space:      [unused] /home/tackang/catkin_ws/install
Log Space:         [missing] /home/tackang/catkin_ws/logs
Source Space:       [exists] /home/tackang/catkin_ws/src
DESTDIR:            [unused] None
------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
------------------------------------------------------------
NOTE: Forcing CMake to run for each package.
------------------------------------------------------------

------------------------------------------------------------
WARNING: Your workspace is not extending any other result
space, but it is set to use a `linked` devel space layout.
This requires the `catkin` CMake package in your source
space in order to be built.
------------------------------------------------------------

[build] Found '3' packages in 0.0 seconds.
[build] Updating package table.
Starting  >>> catkin
_______________________________________________________________________________________________________________________
Warnings   << catkin:cmake /home/tackang/catkin_ws/logs/catkin/build.cmake.000.log
CMake Deprecation Warning at /usr/src/googletest/CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at /usr/src/googletest/googlemock/CMakeLists.txt:45 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at /usr/src/googletest/googletest/CMakeLists.txt:56 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


cd /home/tackang/catkin_ws/build/catkin; catkin build --get-env catkin | catkin env -si  /home/tackang/.local/bin/cmake /home/tackang/catkin_ws/src/catkin --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/tackang/catkin_ws/devel/.private/catkin -DCMAKE_INSTALL_PREFIX=/home/tackang/catkin_ws/install; cd -

.......................................................................................................................
Finished  <<< catkin                       [ 6.1 seconds ]
Starting  >>> glow
_______________________________________________________________________________________________________________________
Errors     << glow:cmake /home/tackang/catkin_ws/logs/glow/build.cmake.000.log
CMake Deprecation Warning at /usr/src/googletest/CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at /usr/src/googletest/googlemock/CMakeLists.txt:45 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at /usr/src/googletest/googletest/CMakeLists.txt:56 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


/home/tackang/catkin_ws/devel/.private/glow/env.sh: 4: /tmp/setup.sh.TwgdtnwNYE: Syntax error: "(" unexpected
Traceback (most recent call last):
  File "/home/tackang/catkin_ws/build/glow/catkin_generated/generate_cached_setup.py", line 22, in <module>
    code = generate_environment_script('/home/tackang/catkin_ws/devel/.private/glow/env.sh')
  File "/home/tackang/catkin_ws/src/catkin/cmake/../python/catkin/environment_cache.py", line 62, in generate_environment_script
    output = subprocess.check_output([env_script, sys.executable, '-c', python_code])
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/tackang/catkin_ws/devel/.private/glow/env.sh', '/usr/bin/python3.8', '-c', 'import os; print(dict(os.environ))']' returned non-zero exit status 2.
CMake Error at /home/tackang/catkin_ws/src/catkin/cmake/safe_execute_process.cmake:11 (message):
  execute_process(/usr/bin/python3.8
  "/home/tackang/catkin_ws/build/glow/catkin_generated/generate_cached_setup.py")
  returned error code 1
Call Stack (most recent call first):
  /home/tackang/catkin_ws/src/catkin/cmake/all.cmake:208 (safe_execute_process)
  /home/tackang/catkin_ws/devel/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:10 (find_package)


cd /home/tackang/catkin_ws/build/glow; catkin build --get-env glow | catkin env -si  /home/tackang/.local/bin/cmake /home/tackang/catkin_ws/src/glow --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/tackang/catkin_ws/devel/.private/glow -DCMAKE_INSTALL_PREFIX=/home/tackang/catkin_ws/install; cd -

.......................................................................................................................
Failed     << glow:cmake                   [ Exited with code 1 ]
Failed    <<< glow                         [ 10.9 seconds ]
Abandoned <<< point_labeler                [ Unrelated job failed ]
[build] Summary: 1 of 3 packages succeeded.
[build]   Ignored:   None.
[build]   Warnings:  1 packages succeeded with warnings.
[build]   Abandoned: 1 packages were abandoned.
[build]   Failed:    1 packages failed.
[build] Runtime: 17.0 seconds total.
[build] Note: Workspace packages have changed, please re-source setup files to use them.`



Thus When I tried to build glow alone, I face thise

```
Not searching for unused variables given on the command line.
-- Using CATKIN_DEVEL_PREFIX: /home/tackang/catkin_ws/devel/.private/glow
-- Using CMAKE_PREFIX_PATH: /home/tackang/catkin_ws/devel
-- This workspace overlays: /home/tackang/catkin_ws/devel
-- Using PYTHON_EXECUTABLE: /usr/bin/python3.8
-- Using Debian Python package layout
-- Using empy: /usr/lib/python3/dist-packages/em.py
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/tackang/catkin_ws/build/glow/test_results
-- Forcing gtest/gmock from source, though one was otherwise available.
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Found gmock sources under '/usr/src/googletest': gmock will be built
CMake Deprecation Warning at /usr/src/googletest/CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at /usr/src/googletest/googlemock/CMakeLists.txt:45 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at /usr/src/googletest/googletest/CMakeLists.txt:56 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- nosetests not found, Python tests can not be run (try installing package 'python3-nose')
-- catkin 0.8.10
-- BUILD_SHARED_LIBS is on
/home/tackang/catkin_ws/devel/.private/glow/env.sh: 4: /tmp/setup.sh.Eva2TmjBJ1: Syntax error: "(" unexpected
Traceback (most recent call last):
  File "/home/tackang/catkin_ws/build/glow/catkin_generated/generate_cached_setup.py", line 22, in <module>
    code = generate_environment_script('/home/tackang/catkin_ws/devel/.private/glow/env.sh')
  File "/home/tackang/catkin_ws/src/catkin/cmake/../python/catkin/environment_cache.py", line 62, in generate_environment_script
    output = subprocess.check_output([env_script, sys.executable, '-c', python_code])
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/tackang/catkin_ws/devel/.private/glow/env.sh', '/usr/bin/python3.8', '-c', 'import os; print(dict(os.environ))']' returned non-zero exit status 2.
CMake Error at /home/tackang/catkin_ws/src/catkin/cmake/safe_execute_process.cmake:11 (message):
  execute_process(/usr/bin/python3.8
  "/home/tackang/catkin_ws/build/glow/catkin_generated/generate_cached_setup.py")
  returned error code 1
Call Stack (most recent call first):
  /home/tackang/catkin_ws/src/catkin/cmake/all.cmake:208 (safe_execute_process)
  /home/tackang/catkin_ws/devel/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:10 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/tackang/catkin_ws/build/glow/CMakeFiles/CMakeOutput.log".
See also "/home/tackang/catkin_ws/build/glow/CMakeFiles/CMakeError.log".
```

**Comment by IrohXu** [comment]
Meet a similar problem:
Server:~/tools/catkin_ws/src/point_labeler/bin$ ./labeler
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Aborted (core dumped)

**Comment by DonghunP** [comment]
@IrohXu  Same Problem
