### ISSUE TITLE
can not load all points

### ISSUE THREAD

**Issue by suya314** [jbehley/point_labeler#51]
Hi, Thanks to your open-source tool.

I want to annotate my own dataset, but point labeler can't load all points of my bin file.

The point cloud has 138,958,718 points, but 75,155,734 points are loaded.
I tried to change some options in settings.cfg, It still can't load all points.

This is original point cloud:
![스크린샷, 2022-05-14 14-38-22](https://user-images.githubusercontent.com/69028945/168412691-3824026d-7a4c-4e45-8567-6114ae9d1f20.png)

load it on point labeler:
![스크린샷, 2022-05-14 14-39-11](https://user-images.githubusercontent.com/69028945/168412697-ffc5979e-f06a-4915-b682-5903e471fa24.png)

What should I do?

**Comment by jbehley** [comment]
For KITTI, we have the option to not load points around the center of a scan as these are points on the car itself. Therefore, you can add the option to the `settings.cfg`:
```yaml
add car points: true # add points at the origin of the sensor possibly caused by the car itself. Default: false.
```

Hope that helps.

**Comment by suya314** [comment]
Thanks for your reply!! 
but I already have tried it and nothing changed...

**Comment by suya314** [comment]
Thanks for your reply!!!
But I already have tried it but nothing changed....

**Comment by jbehley** [comment]
it is really hard to say what is maybe the problem without seeing the data... that points are missing in the middle is most likely due to the "remove car" point option...but if you checked this already, I have no idea what could be the problem. Are you producing x,y,z, remission values? Are these remissions maybe just "1" or something like this such that it produces "white "points"?

**Comment by jbehley** [comment]
it seems like there is no update on this issue, so I close it for now. If you have further questions, then feel free to re-open the issue.
